# Generated by Django 2.0.7 on 2018-08-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='PATH',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='DATE',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='FILE',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='NAME',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='SIZE',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='TYPE',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
