# Generated by Django 2.0.7 on 2018-08-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0003_auto_20180806_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMERO', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='PATH',
        ),
        migrations.RemoveField(
            model_name='object',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='bookName',
        ),
        migrations.AddField(
            model_name='book',
            name='imgsPATH',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='STACK',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bookupload.Stack'),
        ),
        migrations.AddField(
            model_name='stack',
            name='BOOK',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bookupload.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='NAME',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='SIZE',
            field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name='page',
            name='BOOK',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bookupload.Book'),
        ),
        migrations.AddField(
            model_name='stack',
            name='PAGE',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bookupload.Page'),
        ),
    ]
