# Generated by Django 2.0.7 on 2018-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0004_auto_20180807_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='PAGINA',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
