# Generated by Django 2.0.7 on 2018-08-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0005_page_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='capaPATH',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
