# Generated by Django 2.0.7 on 2018-08-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0006_book_capapath'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='PAGES',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
