# Generated by Django 2.0.7 on 2018-08-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0007_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='BOOK',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='PAGE',
        ),
        migrations.RemoveField(
            model_name='object',
            name='STACK',
        ),
        migrations.AddField(
            model_name='object',
            name='BOOK',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bookupload.Book'),
        ),
        migrations.AddField(
            model_name='object',
            name='PAGE',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bookupload.Page'),
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
    ]
