# Generated by Django 2.0.7 on 2018-08-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0008_auto_20180809_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mainPATH',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
