# Generated by Django 2.1.1 on 2018-11-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0009_book_mainpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_x', models.BigIntegerField(blank=True, null=True)),
                ('_y', models.BigIntegerField(blank=True, null=True)),
                ('_sizeX', models.BigIntegerField(blank=True, null=True)),
                ('_sizeof', models.BigIntegerField(blank=True, null=True)),
                ('_orgWidth', models.BigIntegerField(blank=True, null=True)),
                ('_orgHeigth', models.BigIntegerField(blank=True, null=True)),
                ('_type', models.CharField(blank=True, max_length=500, null=True)),
                ('_color', models.CharField(blank=True, max_length=500, null=True)),
                ('_lineWidth', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='BOOK',
        ),
        migrations.RemoveField(
            model_name='object',
            name='PAGE',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='capaPATH',
            new_name='_dirPath',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='imgsPATH',
            new_name='_imgsPath',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='PAGES',
            new_name='_pages',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='BOOK',
            new_name='_book',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='PAGINA',
            new_name='_filename',
        ),
        migrations.RemoveField(
            model_name='book',
            name='NAME',
        ),
        migrations.RemoveField(
            model_name='book',
            name='SIZE',
        ),
        migrations.RemoveField(
            model_name='book',
            name='mainPATH',
        ),
        migrations.RemoveField(
            model_name='page',
            name='NUMERO',
        ),
        migrations.AddField(
            model_name='book',
            name='_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='_page',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.AddField(
            model_name='markup',
            name='_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bookupload.Book'),
        ),
        migrations.AddField(
            model_name='markup',
            name='_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bookupload.Page'),
        ),
    ]
