# Generated by Django 2.1.2 on 2018-11-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0010_auto_20181106_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markup',
            old_name='_sizeof',
            new_name='_sizeY',
        ),
    ]
