# Generated by Django 2.1.2 on 2018-11-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookupload', '0011_auto_20181113_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markup',
            old_name='_orgHeigth',
            new_name='_orgHeight',
        ),
    ]
